# Generated by Django 5.1 on 2024-08-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    def populate_vendas(apps, schema_editor):
        Vendas = apps.get_model('crew', 'Vendas')
        Vendas.objects.create(nome='Produto A', quantidade=10, preco=19.99, total=199.90)
        Vendas.objects.create(nome='Produto B', quantidade=5, preco=29.99, total=149.95)
        Vendas.objects.create(nome='Produto C', quantidade=7, preco=39.99, total=279.93)
        Vendas.objects.create(nome='Produto D', quantidade=3, preco=49.99, total=149.97)
        Vendas.objects.create(nome='Produto E', quantidade=2, preco=59.99, total=119.98)

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_vendas),
    ]
